spring:
  profiles:
    active: local
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.0.5:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&tinyInt1isBit=false
      username: zidol
      password: qwer1234!@#$
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://192.168.0.5:3306/community2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&tinyInt1isBit=false
      username: zidol
      password: qwer1234!@#$
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080